#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Point {
    float x;
    float y;
    float z;
};

layout(set = 0, binding = 0) buffer InputData {
    Point input_points[];
};

layout(set = 0, binding = 1) uniform Params {
    vec3 min_coordinate;
    float inv_vox;
    float scale;
    float inv_scale;
    uint hash_mask;
};

layout(set = 0, binding = 2) buffer OutputData {
    Point output_points[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < input_points.length()) {
        output_points[idx].x = input_points[idx].x * scale;
        output_points[idx].y = input_points[idx].y * scale;
        output_points[idx].z = input_points[idx].z * scale;
    }
}